movie_titles = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "The Godfather Part II",
    "12 Angry Men",
    "Schindler's List",
    "The Lord of the Rings: The Return of the King",
    "Pulp Fiction",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Good, the Bad and the Ugly",
    "Spider-Man: Across the Spider-Verse",
    "Forrest Gump",
    "Fight Club",
    "The Lord of the Rings: The Two Towers",
    "Inception",
    "Star Wars: Episode V - The Empire Strikes Back",
    "The Matrix",
    "Goodfellas",
    "One Flew Over the Cuckoo's Nest",
    "Se7en",
    "It's a Wonderful Life",
    "Seven Samurai",
    "The Silence of the Lambs",
    "Saving Private Ryan",
    "City of God",
    "Interstellar",
    "Life Is Beautiful",
    "The Green Mile",
    "Star Wars: Episode IV - A New Hope",
    "Terminator 2: Judgment Day",
    "Back to the Future",
    "Spirited Away",
    "The Pianist",
    "Psycho",
    "Parasite",
    "Léon: The Professional",
    "The Lion King",
    "Gladiator",
    "American History X",
    "The Departed",
    "Whiplash",
    "The Prestige",
    "The Usual Suspects",
    "Casablanca",
    "Grave of the Fireflies",
    "Harakiri",
    "The Intouchables",
    "Modern Times",
    "Once Upon a Time in the West",
    "Cinema Paradiso",
    "Rear Window",
    "Alien",
    "City Lights",
    "Apocalypse Now",
    "Memento",
    "Django Unchained",
    "Indiana Jones and the Raiders of the Lost Ark",
    "WALL·E",
    "The Lives of Others",
    "Sunset Blvd.",
    "Paths of Glory",
    "Avengers: Infinity War",
    "The Shining",
    "The Great Dictator",
    "Witness for the Prosecution",
    "Spider-Man: Into the Spider-Verse",
    "Aliens",
    "American Beauty",
    "The Dark Knight Rises",
    "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    "Inglourious Basterds",
    "Oldboy",
    "Coco",
    "Amadeus",
    "Toy Story",
    "Braveheart",
    "Das Boot",
    "Joker",
    "Avengers: Endgame",
    "Princess Mononoke",
    "Good Will Hunting",
    "Once Upon a Time in America",
    "Your Name.",
    "3 Idiots",
    "Singin' in the Rain",
    "High and Low",
    "Requiem for a Dream",
    "Capernaum",
    "Toy Story 3",
    "Star Wars: Episode VI - Return of the Jedi",
    "Come and See",
    "Eternal Sunshine of the Spotless Mind",
    "2001: A Space Odyssey",
    "The Hunt",
    "Reservoir Dogs",
    "Lawrence of Arabia",
    "Citizen Kane",
    "M",
    "Ikiru",
    "North by Northwest",
    "The Apartment",
    "The Secret in Their Eyes",
    "The Bridge on the River Kwai",
    "Blade Runner",
    "The Seventh Seal",
    "Incendies",
    "The Gold Rush",
    "The General",
    "The Bandit",
    "Three Billboards Outside Ebbing, Missouri",
    "My Neighbor Totoro",
    "Sherlock Jr.",
    "The Secret Life of Walter Mitty",
    "Before Sunrise",
    "The Grand Budapest Hotel",
    "The Wages of Fear",
    "The Big Lebowski",
    "Logan",
    "Gone Girl",
    "Wild Strawberries",
    "Hacksaw Ridge",
    "Memories of Murder",
    "Mary and Max",
    "The 400 Blows",
    "Prisoners",
    "A Silent Voice",
    "The Truman Show",
    "It Happened One Night",
    "The Night of the Hunter",
    "The Passion of Joan of Arc",
    "The Battle of Algiers",
    "Before Sunset",
    "The Best Years of Our Lives",
    "The Cabinet of Dr. Caligari",
    "Tokyo Story",
    "Infernal Affairs",
    "Spotlight",
    "The Hunt",
    "How to Train Your Dragon",
    "Into the Wild",
    "Mr. Smith Goes to Washington",
    "The Secret World of Arrietty",
    "Before Midnight",
    "In the Mood for Love",
    "La Haine",
    "The Best of Youth",
    "Beauty and the Beast",
    "The Princess Bride",
    "The Handmaiden",
    "The Help",
    "The Lives of Others",
    "Nausicaä of the Valley of the Wind",
    "The Incredibles",
    "Castle in the Sky",
    "The Diving Bell and the Butterfly",
    "The Grapes of Wrath",
    "Warrior",
    "Hotel Rwanda",
    "The Red Shoes",
    "Before the Devil Knows You're Dead",
    "Monsters, Inc.",
    "The Terminator",
    "The Battle of San Pietro",
    "Grave of the Fireflies",
    "The Iron Giant",
    "La Dolce Vita",
    "Memories of Underdevelopment",
    "The Cranes Are Flying",
    "Gandhi",
    "The Great Beauty",
    "Roman Holiday",
    "Stand by Me",
    "The Night Comes for Us",
    "Let the Right One In",
    "The Salt of the Earth",
    "The Sea Inside"
]



